services:
  oneunit-webbsida:
    build:
      context: .
      dockerfile: Dockerfile
    image: oneunit-webbsida:latest
    container_name: oneunit-webbsida
    restart: unless-stopped
    ports:
      - "3001:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
